### ISSUE TITLE
Make hotspot directly pluggable onto screen

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#68]
In GitLab by @Popolechien on Nov 1, 2019, 10:31

So we have a use case where everyone in the room has a tablet or smartphone but the teacher also wants to showcase on a large screen (projector or TV screen). Ideally, we could/should be able to simply plug the hotspot onto it and have visual display.

**Comment by benoit74** [comment]
I wanted to experiment with this, and I finally more or less achieved to make it work.

Sample code for docker-compose yml (`/etc/docker/compose.yml`, config below is for demo image or any hotspot named `wikipedia`):
```
services:
  browser:
    image: bh.cr/balenalabs/browser-aarch64:v2.9.0
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    environment:
      SHOW_CURSOR: 1
      LAUNCH_URL: http://wikipedia.hotspot
```

I also had to edit the /etc/hosts inside this container to add proper DNS records (DNS to the hotspot is not working from inside the container) ; I just added wikipedia.hotspot and kiwix.wikipedia.hotspot pointing to 192.168.2.1 for my tests, more entries are obviously needed, and this does not survive a hotspot restart.

The image size is not negligible (I don't have precise numbers, dive is not working for some reason on my machine with this image ... but it is more than 600M).

The whole stack is pretty slow on a Raspberry Pi 3 Model B, but still usable if you are a bit patient. Probably drains quite a lot of battery. I can't check how it runs on a Pi 5 ... because I don't have proper HDMI cable ... stay tuned!
